Fix CLI fails when running on the tests (#661)
Running:
  precli -r tests

Yields the following error:

  TypeError: all() takes exactly one argument (3 given)

The recent change to is_test_code() is not using a collection passed to
the all() function.

Signed-off-by: Eric Brown <eric.brown@securesauce.dev>