Fix --gist argument failure (#677)
This change fixes --gist argument which was raising a traceback. Also
adds a unit test of the condition where --gist is specified but
GITHUB_TOKEN is undefined.

```
Traceback (most recent call last):
  File "/Users/ericwb/workspace/precli/.tox/py313/bin/precli", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/Users/ericwb/workspace/precli/precli/cli/main.py", line 306, in main
    create_gist(file, renderer)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/Users/ericwb/workspace/precli/precli/cli/main.py", line 238, in create_gist
    "files": {filename: {"content": file_content}},
              ^^^^^^^^
UnboundLocalError: cannot access local variable 'filename' where it is not associated with a value
```

Signed-off-by: Eric Brown <eric.brown@securesauce.dev>